import type { Language } from './types';

export const COLORS = {
  primary: '#0F766E',
  primaryDark: '#115E59',
  primaryLight: '#14B8A6',
  primaryTint: '#CCFBF1',
  primaryBg: '#F0FDFA',
  accent: '#F59E0B',
  accentLight: '#FBBF24',
  accentTint: '#FEF3C7',
  success: '#16A34A',
  successTint: '#DCFCE7',
  danger: '#DC2626',
  dangerTint: '#FEE2E2',
  warning: '#EA580C',
  warningTint: '#FFEDD5',
  neutral0: '#FFFFFF',
  neutral50: '#F8FAFC',
  neutral100: '#F1F5F9',
  neutral200: '#E2E8F0',
  neutral300: '#CBD5E1',
  neutral400: '#94A3B8',
  neutral500: '#64748B',
  neutral600: '#475569',
  neutral700: '#334155',
  neutral800: '#1E293B',
  neutral900: '#0F172A',
} as const;

export const translations = {
  appName: { EN: 'KH Invoice', KH: 'វិក្កយបត្រ' },
  signIn: { EN: 'Sign In', KH: 'ចូលប្រើ' },
  signUp: { EN: 'Sign Up', KH: 'ចុះឈ្មោះ' },
  signOut: { EN: 'Sign Out', KH: 'ចាកចេញ' },
  phone: { EN: 'Phone Number', KH: 'លេខទូរស័ព្ទ' },
  password: { EN: 'Password', KH: 'ពាក្យសម្ងាត់' },
  businessName: { EN: 'Business Name', KH: 'ឈ្មោះអាជីព' },
  username: { EN: 'Username', KH: 'ឈ្មោះអ្នកប្រើ' },
  dashboard: { EN: 'Dashboard', KH: 'ផ្ទាំងគ្រប់គ្រង' },
  transactions: { EN: 'Transactions', KH: 'ប្រតិបត្តិការ' },
  invoices: { EN: 'Invoices', KH: 'វិក្កយបត្រ' },
  products: { EN: 'Products', KH: 'ផលិតផល' },
  profile: { EN: 'Profile', KH: 'ប្រវត្តិរូប' },
  income: { EN: 'Income', KH: 'ចំណូល' },
  expense: { EN: 'Expense', KH: 'ចំណាយ' },
  balance: { EN: 'Balance', KH: 'សមតុភាព' },
  total: { EN: 'Total', KH: 'សរុប' },
  add: { EN: 'Add', KH: 'បន្ថែម' },
  edit: { EN: 'Edit', KH: 'កែសម្រួល' },
  delete: { EN: 'Delete', KH: 'លុប' },
  save: { EN: 'Save', KH: 'រក្សាទុក' },
  cancel: { EN: 'Cancel', KH: 'បោះបង់' },
  description: { EN: 'Description', KH: 'ការពិពណ៌នា' },
  quantity: { EN: 'Quantity', KH: 'បរិមាណ' },
  unit: { EN: 'Unit', KH: 'ឯកតា' },
  unitPrice: { EN: 'Unit Price', KH: 'តម្លៃឯកតា' },
  amount: { EN: 'Amount', KH: 'ចំនួនទឹកប្រាក់' },
  date: { EN: 'Date', KH: 'កាលបរិច្ឆេទ' },
  customerName: { EN: 'Customer Name', KH: 'ឈ្មោះអតិថិជន' },
  customerPhone: { EN: 'Customer Phone', KH: 'លេខអតិថិជន' },
  invoiceNumber: { EN: 'Invoice #', KH: 'លេខវិក្កយបត្រ' },
  status: { EN: 'Status', KH: 'ស្ថានភាព' },
  paid: { EN: 'Paid', KH: 'បង់រួច' },
  unpaid: { EN: 'Unpaid', KH: 'មិនទាន់បង់' },
  partial: { EN: 'Partial', KH: 'បង់មួយចំនួន' },
  stock: { EN: 'Stock', KH: 'ស្តុក' },
  lowStock: { EN: 'Low Stock', KH: 'ស្តុកតិច' },
  inStock: { EN: 'In Stock', KH: 'មានស្តុក' },
  outOfStock: { EN: 'Out of Stock', KH: 'អស់ស្តុក' },
  costPrice: { EN: 'Cost Price', KH: 'តម្លៃដើម' },
  sellPrice: { EN: 'Sell Price', KH: 'តម្លៃលក់' },
  recentTransactions: { EN: 'Recent Transactions', KH: 'ប្រតិបត្តិការថ្មីៗ' },
  noData: { EN: 'No data yet', KH: 'មិនទាន់មានទិន្នន័យ' },
  noTransactions: { EN: 'No transactions yet', KH: 'មិនទាន់មានប្រតិបត្តិការ' },
  noInvoices: { EN: 'No invoices yet', KH: 'មិនទាន់មានវិក្កយបត្រ' },
  noProducts: { EN: 'No products yet', KH: 'មិនទាន់មានផលិតផល' },
  loading: { EN: 'Loading...', KH: 'កំពុងផ្ទុក...' },
  error: { EN: 'Error', KH: 'កំហុស' },
  networkError: { EN: 'Network error', KH: 'កំហុសបណ្តាញ' },
  welcome: { EN: 'Welcome', KH: 'សូមស្វាគមន៍' },
  overview: { EN: 'Overview', KH: 'ទិដ្ឋភាពរួម' },
  thisMonth: { EN: 'This Month', KH: 'ខែនេះ' },
  today: { EN: 'Today', KH: 'ថ្ងៃនេះ' },
  totalIncome: { EN: 'Total Income', KH: 'ចំណូលសរុប' },
  totalExpense: { EN: 'Total Expense', KH: 'ចំណាយសរុប' },
  netProfit: { EN: 'Net Profit', KH: 'ប្រាក់ចំណេញសុទ្ធ' },
  addTransaction: { EN: 'Add Transaction', KH: 'បន្ថែមប្រតិបត្តិការ' },
  addInvoice: { EN: 'Create Invoice', KH: 'បង្កើតវិក្កយបត្រ' },
  addProduct: { EN: 'Add Product', KH: 'បន្ថែមផលិតផល' },
  search: { EN: 'Search', KH: 'ស្វែងរក' },
  settings: { EN: 'Settings', KH: 'ការកំណត់' },
  language: { EN: 'Language', KH: 'ភាសា' },
  items: { EN: 'Items', KH: 'ធាតុ' },
  subtotal: { EN: 'Subtotal', KH: 'សរុបរង' },
  paidAmount: { EN: 'Paid Amount', KH: 'ចំនួនបង់' },
  balanceDue: { EN: 'Balance Due', KH: 'សមតុភាពនៅសល់' },
  recordPayment: { EN: 'Record Payment', KH: 'កត់ត្រាប្រាក់' },
  viewDetails: { EN: 'View Details', KH: 'មើលព័ត៌មានលម្អិត' },
  back: { EN: 'Back', KH: 'ត្រឡប់' },
  confirm: { EN: 'Confirm', KH: 'បញ្ជាក់' },
  confirmDelete: { EN: 'Are you sure you want to delete?', KH: 'តើអ្នកប្រាកដថាចង់លុបឬទេ?' },
  all: { EN: 'All', KH: 'ទាំងអស់' },
  active: { EN: 'Active', KH: 'សកម្ម' },
  inactive: { EN: 'Inactive', KH: 'មិនសកម្ម' },
} as const;

export function t(key: keyof typeof translations, lang: Language): string {
  return translations[key][lang];
}
