import type { Language } from './types';

/* ── Uniform Colors — same on every screen ── */
export const C = {
  primary: '#1B4F72',
  primaryLight: '#2E86C1',
  primaryDark: '#0E3A5E',
  primaryTint: '#D6EAF8',
  primaryBg: '#EBF5FB',
  accent: '#D4A017',
  accentTint: '#FCF3CF',
  success: '#1E8449',
  successTint: '#D5F5E3',
  danger: '#C0392B',
  dangerTint: '#FADBD8',
  warning: '#E67E22',
  warningTint: '#FDEBD0',
  n0: '#FFFFFF', n50: '#F8F9FA', n100: '#F1F3F5', n200: '#E5E8EB', n300: '#CED4DA',
  n400: '#ADB5BD', n500: '#6C757D', n600: '#495057', n700: '#343A40', n800: '#212529', n900: '#161A1D',
} as const;

export const t = {
  appName: { EN: 'KH Invoice', KH: 'វិក្កយបត្រ' },
  signIn: { EN: 'Sign In', KH: 'ចូលប្រើ' },
  signUp: { EN: 'Sign Up', KH: 'ចុះឈ្មោះ' },
  signOut: { EN: 'Sign Out', KH: 'ចាកចេញ' },
  phone: { EN: 'Phone Number', KH: 'លេខទូរស័ព្ទ' },
  password: { EN: 'Password', KH: 'ពាក្យសម្ងាត់' },
  businessName: { EN: 'Business Name', KH: 'ឈ្មោះអាជីព' },
  username: { EN: 'Username', KH: 'ឈ្មោះអ្នកប្រើ' },
  dashboard: { EN: 'Dashboard', KH: 'ផ្ទាំងគ្រប់គ្រង' },
  transactions: { EN: 'Transactions', KH: 'ប្រតិបត្តិការ' },
  invoices: { EN: 'Invoices', KH: 'វិក្កយបត្រ' },
  products: { EN: 'Products', KH: 'ផលិតផល' },
  profile: { EN: 'Profile', KH: 'ប្រវត្តិរូប' },
  income: { EN: 'Income', KH: 'ចំណូល' },
  expense: { EN: 'Expense', KH: 'ចំណាយ' },
  balance: { EN: 'Balance', KH: 'សមតុភាព' },
  total: { EN: 'Total', KH: 'សរុប' },
  add: { EN: 'Add', KH: 'បន្ថែម' },
  edit: { EN: 'Edit', KH: 'កែសម្រួល' },
  delete: { EN: 'Delete', KH: 'លុប' },
  save: { EN: 'Save', KH: 'រក្សាទុក' },
  cancel: { EN: 'Cancel', KH: 'បោះបង់' },
  description: { EN: 'Description', KH: 'ការពិពណ៌នា' },
  quantity: { EN: 'Quantity', KH: 'បរិមាណ' },
  unit: { EN: 'Unit', KH: 'ឯកតា' },
  unitPrice: { EN: 'Unit Price', KH: 'តម្លៃឯកតា' },
  amount: { EN: 'Amount', KH: 'ចំនួនទឹកប្រាក់' },
  date: { EN: 'Date', KH: 'កាលបរិច្ឆេទ' },
  customerName: { EN: 'Customer Name', KH: 'ឈ្មោះអតិថិជន' },
  customerPhone: { EN: 'Customer Phone', KH: 'លេខអតិថិជន' },
  invoiceNumber: { EN: 'Invoice #', KH: 'លេខវិក្កយបត្រ' },
  status: { EN: 'Status', KH: 'ស្ថានភាព' },
  paid: { EN: 'Paid', KH: 'បង់រួច' },
  unpaid: { EN: 'Unpaid', KH: 'មិនទាន់បង់' },
  partial: { EN: 'Partial', KH: 'បង់មួយចំនួន' },
  stock: { EN: 'Stock', KH: 'ស្តុក' },
  lowStock: { EN: 'Low Stock', KH: 'ស្តុកតិច' },
  inStock: { EN: 'In Stock', KH: 'មានស្តុក' },
  outOfStock: { EN: 'Out of Stock', KH: 'អស់ស្តុក' },
  costPrice: { EN: 'Cost Price', KH: 'តម្លៃដើម' },
  sellPrice: { EN: 'Sell Price', KH: 'តម្លៃលក់' },
  recentTransactions: { EN: 'Recent Transactions', KH: 'ប្រតិបត្តិការថ្មីៗ' },
  noTransactions: { EN: 'No transactions yet', KH: 'មិនទាន់មានប្រតិបត្តិការ' },
  noInvoices: { EN: 'No invoices yet', KH: 'មិនទាន់មានវិក្កយបត្រ' },
  noProducts: { EN: 'No products yet', KH: 'មិនទាន់មានផលិតផល' },
  loading: { EN: 'Loading...', KH: 'កំពុងផ្ទុក...' },
  networkError: { EN: 'Network error', KH: 'កំហុសបណ្តាញ' },
  welcome: { EN: 'Welcome', KH: 'សូមស្វាគមន៍' },
  thisMonth: { EN: 'This Month', KH: 'ខែនេះ' },
  totalIncome: { EN: 'Total Income', KH: 'ចំណូលសរុប' },
  totalExpense: { EN: 'Total Expense', KH: 'ចំណាយសរុប' },
  netProfit: { EN: 'Net Profit', KH: 'ប្រាក់ចំណេញសុទ្ធ' },
  addTransaction: { EN: 'Add Transaction', KH: 'បន្ថែមប្រតិបត្តិការ' },
  addInvoice: { EN: 'Create Invoice', KH: 'បង្កើតវិក្កយបត្រ' },
  addProduct: { EN: 'Add Product', KH: 'បន្ថែមផលិតផល' },
  language: { EN: 'Language', KH: 'ភាសា' },
  subtotal: { EN: 'Subtotal', KH: 'សរុបរង' },
  paidAmount: { EN: 'Paid Amount', KH: 'ចំនួនបង់' },
  balanceDue: { EN: 'Balance Due', KH: 'សមតុភាពនៅសល់' },
  confirmDelete: { EN: 'Are you sure you want to delete?', KH: 'តើអ្នកប្រាកដថាចង់លុបឬទេ?' },
  all: { EN: 'All', KH: 'ទាំងអស់' },
} as const;

export function tr(key: keyof typeof t, lang: Language): string {
  return t[key][lang];
}
